# Generated by Django 5.0.1 on 2024-02-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planet_type', models.CharField(choices=[('N/A', 'Unknown'), ('TP', 'Terrestial Planet'), ('GG', 'Gas Giant'), ('IG', 'Ice Giant'), ('DP', 'Dwarf Planet')], max_length=3)),
                ('mass', models.DecimalField(decimal_places=5, max_digits=10)),
                ('equitorial_diameter', models.DecimalField(decimal_places=4, max_digits=6)),
                ('semi_major_axis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orbital_period', models.DecimalField(decimal_places=2, max_digits=7)),
                ('inclination_to_the_ecliptic', models.DecimalField(decimal_places=3, max_digits=5)),
                ('orbital_eccentricity', models.DecimalField(decimal_places=3, max_digits=4)),
                ('rotation_period', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confirmed_moons', models.PositiveSmallIntegerField()),
                ('axial_tilt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rings', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('N/A', 'Unknown')], max_length=3)),
                ('atmosphere', models.CharField(max_length=200)),
            ],
        ),
    ]
